sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.haxelib-local/

language: scala

scala:
  - 2.11.7
  - 2.10.6

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - mono-devel
    - libgc1c2

before_install:
  - mkdir /tmp/untar
  - travis_retry wget --output-document=/tmp/neko.tar.gz http://nekovm.org/media/neko-2.0.0-linux64.tar.gz
  - tar zxvf /tmp/neko.tar.gz -C /tmp/untar/
  - mv /tmp/untar/neko-*/ /opt/neko/
  - travis_retry wget --output-document=/tmp/haxe.tar.gz http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/"$HAXE_FILE"
  - tar zxvf /tmp/haxe.tar.gz -C /tmp/untar/
  - mv /tmp/untar/haxe-*/ /opt/haxe/
  - export PATH=$PATH:/opt/haxe:/opt/neko
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/neko
  - export HAXE_STD_PATH=/opt/haxe/haxe/std
  - haxelib setup $HOME/.haxelib-local
  - travis_retry haxelib install hxjava --always

install:
  - sbt ";++$TRAVIS_SCALA_VERSION;haxelibInstallDependencies;update"

script:
  - sbt ";++$TRAVIS_SCALA_VERSION;$SBT_COMMAND"

before_cache:
  - find $HOME/.sbt -name '*.lock' | xargs rm
  - find $HOME/.ivy2 -name 'ivydata-*.properties' | xargs rm

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0e11823ea12783811cd8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  matrix:
    # Haxe 3.2.0
    - SBT_COMMAND=test; HAXE_FILE=haxe_2015-05-12_master_77d171b.tar.gz

    # Haxe 3.2.1
    - SBT_COMMAND=test; HAXE_FILE=haxe_2015-10-12_master_deab442.tar.gz

before_deploy:
  - travis_retry git clone --depth=1 $secret_git ./secret
  - bash ./secret/before_deploy.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    scala: 2.11.7
    condition: -e ./deploy.sh && "$HAXE_FILE" == "haxe_2015-05-12_master_77d171b.tar.gz"
    all_branches: true
