language: scala

scala:
  - 2.11.7
  - 2.10.6

jdk:
  - oraclejdk8

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq haxe
 - travis_retry sudo haxelib setup .haxelib
 - travis_retry sudo haxelib install hxjava
 - travis_retry sudo haxelib install continuation
 - travis_retry sudo haxelib install hxparse
 - travis_retry sudo haxelib install microbuilder-HUGS

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0e11823ea12783811cd8
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

script:
  - sbt test
  - sbt laika:site && sbt ghpages-push-site
